name: openzoom
version: 0.0.1
author: Daniel Gasienica
description: Library for rendering multiscale images
homepage: http://openzoom.org/
dependencies:
  browser: any
  unittest: any
  xml: ">=2.0.0 <3.0.0"
